const supportiveMessages = [
    "You're making progress every day. Keep it up!",
    "Small steps lead to big changes. You've got this!",
    "Consistency is key, and you're nailing it!",
    "Your dedication is inspiring. Great work!",
    "You're building a better you, one habit at a time.",
    "Remember why you started. You're doing amazing!",
    "Each day is a new opportunity, and you're seizing it!",
    "Your future self will thank you for your efforts today.",
    "You're proving that change is possible. Bravo!",
    "Keep pushing forward. Your persistence is paying off!",
    "You're stronger than you think. Keep going!",
    "Every small victory counts. Celebrate your progress!",
    "You're on the right track. Stay focused!",
    "Your commitment is admirable. You should be proud!",
    "One day at a time, you're transforming your life.",
    "You're creating positive change. Well done!",
    "Your determination is shining through. Keep it up!",
    "You're making it happen. Great job!",
    "Each effort brings you closer to your goals. Fantastic work!",
    "You're proving your strength every day. Impressive!",
    "Your journey is inspiring. Keep moving forward!",
    "You're building momentum. Don't stop now!",
    "Your persistence is paying off. You're doing great!",
    "You're making your future brighter with each choice.",
    "Keep up the fantastic work. You're on a roll!",
    "Your efforts are adding up. Be proud of yourself!",
    "You're showing incredible resilience. Keep pushing!",
    "Every day is a step towards success. You're nailing it!",
    "You're turning challenges into opportunities. Well done!",
    "Your dedication is truly admirable. Keep it up!",
    "You're writing your own success story. Keep going!",
    "Your commitment to change is inspiring. Great job!",
    "You're proving that you can do anything you set your mind to.",
    "Keep believing in yourself. You're doing amazing things!",
    "Your progress is a testament to your strength. Bravo!",
    "You're creating positive habits that will last a lifetime.",
    "Each day, you're getting closer to your goals. Fantastic!",
    "Your determination is unstoppable. Keep pushing forward!",
    "You're making yourself proud. Keep up the great work!",
    "Your efforts today are shaping a better tomorrow. Well done!",
    "You're showing incredible strength. Keep going strong!",
    "Every small win adds up. You're doing fantastic!",
    "Your journey is unique and inspiring. Keep moving forward!",
    "You're proving that change is within your grasp. Great job!",
    "Keep up the momentum. You're on the right path!",
    "Your dedication is paying off. Be proud of your progress!",
    "You're building a stronger version of yourself every day.",
    "Your commitment to improvement is admirable. Keep it up!",
    "You're turning your goals into reality. Impressive work!",
    "Each day is a new opportunity, and you're making the most of it!",
    "Your perseverance is truly inspiring. Don't give up!",
    "You're creating positive change in your life. Well done!",
    "Keep pushing your limits. You're capable of amazing things!",
    "Your efforts are not going unnoticed. Great progress!",
    "You're proving that consistency leads to success. Keep going!",
    "Every step forward is a victory. You're doing great!",
    "Your determination is admirable. Stay focused on your goals!",
    "You're making progress, even when it's hard. Be proud!",
    "Keep believing in yourself. You're on the right track!",
    "Your journey is inspiring others. Keep up the fantastic work!",
    "You're showing incredible resilience. Keep pushing forward!",
    "Every day is a chance to improve, and you're seizing it!",
    "Your commitment to change is paying off. Well done!",
    "You're building the life you want, one habit at a time.",
    "Keep up the great work. Your future self will thank you!",
    "Your dedication is truly remarkable. Don't stop now!",
    "You're proving that you have the power to change. Bravo!",
    "Each small victory is a step towards your bigger goals.",
    "Your perseverance is admirable. Keep going strong!",
    "You're making positive choices every day. Great job!",
    "Keep pushing through challenges. You're getting stronger!",
    "Your efforts are shaping a better future. Well done!",
    "You're showing incredible strength of character. Keep it up!",
    "Every day is progress. You're doing amazingly well!",
    "Your journey is unique and inspiring. Keep moving forward!",
    "You're proving that change is possible with dedication.",
    "Keep up the fantastic work. You're making real progress!",
    "Your commitment to self-improvement is inspiring. Great job!",
    "You're building a better life, one day at a time.",
    "Your persistence is paying off. Don't stop now!",
    "You're making yourself proud every day. Keep going!",
    "Each effort brings you closer to your goals. Well done!",
    "Your determination is truly admirable. Stay strong!",
    "You're creating lasting change. Be proud of yourself!",
    "Keep pushing forward. Your hard work is paying off!",
    "Your dedication to your goals is impressive. Keep it up!",
    "You're proving your strength every single day. Bravo!",
    "Every step forward is a victory. Celebrate your progress!",
    "Your journey is an inspiration. Keep moving forward!",
    "You're showing incredible resilience. Don't give up!",
    "Each day is a new opportunity, and you're making it count!",
    "Your commitment to change is transforming your life.",
    "Keep believing in yourself. You're capable of amazing things!",
    "Your efforts are creating a positive ripple effect. Great work!",
    "You're building momentum towards your goals. Keep pushing!",
    "Every choice you make is shaping your future. Well done!",
    "Your perseverance is truly remarkable. Stay focused!",
    "You're making progress, even when it's challenging. Be proud!",
    "Keep up the fantastic work. You're on the path to success!",
    "Your dedication is paying off in wonderful ways. Keep going!",
    "You're making progress every day. Keep it up!",
    "Fantastic job today! Keep going strong.",
    "Great work! You're on the right track.",
    "Well done! Each day counts.",
    "Awesome effort! You're doing great.",
    "Keep it up! Your hard work is showing.",
    "You're doing amazing! Keep pushing.",
    "Excellent progress! Stay motivated.",
    "Bravo! You're making great strides.",
    "You're doing fantastic! Keep it up.",
    "Great job! You're moving closer to your goal.",
    "Wonderful effort! Keep going.",
    "You're making incredible progress! Keep it up.",
    "Fantastic work! Your dedication is clear.",
    "Well done! You're achieving your goals.",
    "Keep it up! Your progress is inspiring.",
    "Awesome job! You're on track.",
    "Great work today! Keep it going.",
    "You're doing an outstanding job! Keep it up.",
    "Excellent effort! You're making great strides.",
    "Bravo! Your dedication is paying off.",
    "Fantastic progress! Stay focused.",
    "You're doing great! Keep moving forward.",
    "Well done! Your effort is showing.",
    "Keep going! You're making fantastic progress.",
    "Excellent job! Your hard work is paying off.",
    "Great job! Your consistency is impressive.",
    "You're making wonderful progress. Keep it up!",
    "Awesome work! You're achieving your goals.",
    "Well done! You're on the path to success.",
    "Keep it up! You're making a real difference.",
    "Fantastic effort! You're doing an amazing job.",
    "Great progress! Stay motivated and keep going.",
    "You're doing fantastic! Keep pushing forward.",
    "Bravo! Your hard work is evident.",
    "Well done! You're making steady progress.",
    "Keep it up! You're on track to success.",
    "Excellent work! Your dedication is impressive.",
    "You're doing great! Keep up the momentum.",
    "Fantastic job! Your effort is paying off.",
    "Well done! You're achieving your goals.",
    "Keep going! You're making excellent progress.",
    "Awesome job! Your hard work is showing results.",
    "Great work today! You're making a difference.",
    "You're making fantastic progress. Keep going!",
    "Excellent effort! You're on the right track.",
    "Bravo! Your commitment is making a difference.",
    "Well done! You're doing an outstanding job.",
    "Keep it up! Your progress is inspiring.",
    "Fantastic work! You're achieving your goals.",
    "Great job! Keep pushing forward.",
    "You're doing great! Keep up the excellent work.",
    "Awesome effort! You're making fantastic progress.",
    "Well done! Your dedication is evident.",
    "Keep going! You're on the path to success.",
    "Excellent progress! Your hard work is showing.",
    "Bravo! You're making amazing strides.",
    "You're doing fantastic! Keep moving forward.",
    "Great work! Your commitment is paying off.",
    "Well done! You're making remarkable progress.",
    "Keep it up! You're achieving great things.",
    "Fantastic job! Your progress is evident.",
    "Awesome work! You're on track for success.",
    "Well done! Your hard work is truly paying off.",
    "Keep going! You're making a significant difference.",
    "Great effort! Your dedication is clear.",
    "Bravo! You're making fantastic progress.",
    "You're doing amazing! Keep up the great work.",
    "Excellent job! Your commitment is inspiring.",
    "Well done! You're on the path to achieving your goals.",
    "Keep it up! Your progress is impressive.",
    "Fantastic effort! You're doing a great job.",
    "Great work today! Keep pushing forward.",
    "You're making excellent progress. Keep going!",
    "Bravo! Your dedication is truly admirable.",
    "Well done! You're achieving great results.",
    "Keep it up! Your hard work is showing.",
    "Fantastic job! You're making steady progress.",
    "Great job! Your commitment is paying off.",
    "You're doing fantastic! Keep moving forward.",
    "Well done! Your progress is inspiring.",
    "Awesome work! You're on track for success.",
    "Keep going! You're making incredible strides.",
    "Excellent progress! Your effort is evident.",
    "Bravo! You're achieving your goals.",
    "Well done! You're making amazing progress.",
    "Keep it up! Your dedication is impressive.",
    "Fantastic effort! You're doing a great job.",
    "Great work! You're on the path to success.",
    "You're making wonderful progress. Keep going!",
];

const motivationalMessages = [
    "Every step away from the habit is a step toward a better you.",
    "You have the strength to overcome this. Keep pushing forward.",
    "Believe in your ability to change. You've got this!",
    "Each day without the habit is a victory. Celebrate your progress.",
    "You're stronger than you think. Keep going.",
    "Every challenge you overcome makes you more resilient.",
    "Your journey to a healthier you starts with one decision.",
    "Don't give up. Every day is a new chance to improve.",
    "Change is hard, but you're capable of amazing things.",
    "Each day you resist is a step closer to your goal.",
    "You're not alone in this. Keep striving for a better you.",
    "Your future self will thank you for the effort you're putting in.",
    "Stay focused. You have the power to change your life.",
    "Believe in yourself and your ability to overcome this challenge.",
    "You're making progress, even if it doesn't always feel like it.",
    "Keep pushing forward. Every effort counts.",
    "You have the strength within you to break free from this habit.",
    "Success comes from persistence. Stay the course.",
    "You're capable of more than you know. Keep up the fight.",
    "Each day without the habit is a win. Keep going.",
    "Change takes time, but you're making progress every day.",
    "Stay positive. You're on the right path to a healthier life.",
    "You've already achieved so much. Don't stop now.",
    "Your determination will get you through this. Keep pushing.",
    "Remember why you started. You're making great strides.",
    "Every small victory is a step towards a big change.",
    "You're stronger than this habit. Keep fighting.",
    "Believe in your ability to succeed. You're on the right track.",
    "Your efforts are paying off. Stay committed.",
    "You have the power to make positive changes in your life.",
    "Each day you resist brings you closer to your goal.",
    "Stay strong. Your future self will be grateful for your efforts.",
    "Keep moving forward. You're making incredible progress.",
    "You're doing an amazing job. Keep up the hard work.",
    "Success is a journey, and you're making great strides.",
    "Believe in yourself. You have the strength to overcome this.",
    "You're capable of achieving great things. Keep going.",
    "Your commitment is inspiring. Keep pushing through.",
    "You've made it this far. Don't give up now.",
    "Every day is a new opportunity to make positive changes.",
    "You're on the path to success. Stay focused and keep going.",
    "Change is hard, but you're doing it. Keep up the great work.",
    "You have the power to break free from this habit. Keep fighting.",
    "Stay determined. You're making significant progress.",
    "You're doing an incredible job. Keep pushing forward.",
    "Believe in your ability to overcome this challenge.",
    "Each step away from the habit is a step towards success.",
    "Your dedication is making a difference. Keep going.",
    "You're on the right path. Stay strong and keep moving forward.",
    "Remember your goals and stay focused. You've got this.",
    "You have the strength to make this change. Keep going.",
    "Success is within your reach. Keep up the hard work.",
    "You're making progress every day. Stay motivated.",
    "Your determination is your greatest asset. Keep fighting.",
    "Believe in yourself. You are capable of achieving your goals.",
    "Each day without the habit is a victory. Celebrate your progress.",
    "You're doing great. Keep up the effort and stay strong.",
    "Your journey is inspiring. Keep pushing towards your goals.",
    "Stay focused. Your hard work is paying off.",
    "You're stronger than you know. Keep up the fight.",
    "Every day you resist is a day closer to success.",
    "Believe in your ability to overcome this. You're making progress.",
    "You're making a real difference. Keep going.",
    "Stay determined. Your hard work is leading to success.",
    "You've come so far. Don't stop now.",
    "Each step you take brings you closer to breaking free from the habit.",
    "Your commitment is admirable. Keep moving forward.",
    "You have the strength to succeed. Keep pushing.",
    "Believe in your journey. You're making great strides.",
    "You're on the path to success. Keep going.",
    "Your determination is making a difference. Stay strong.",
    "Keep going. Each day is a step towards a better you.",
    "You're doing an amazing job. Keep up the hard work.",
    "Every effort counts. You're making progress.",
    "Stay motivated. You have the power to achieve your goals.",
    "You're capable of making this change. Keep fighting.",
    "Believe in yourself. You're making great progress.",
    "You're doing fantastic. Keep pushing forward.",
    "Every day is a new chance to succeed. Stay focused.",
    "You have the strength to overcome this. Keep going.",
    "Your dedication is paying off. Keep moving forward.",
    "Stay positive. You're making incredible progress.",
    "You're on the right track. Keep pushing forward.",
    "Believe in your ability to succeed. You're doing great.",
    "You're making significant progress. Keep up the effort.",
    "Stay determined. Your hard work is leading to success.",
    "You've got this! Keep fighting and stay focused.",
    "Every step away from the habit is a step towards a better you.",
    "You're making incredible strides. Keep up the great work.",
    "Believe in yourself. You have the strength to succeed.",
    "You're on the path to success. Stay focused and keep going.",
    "Your commitment is inspiring. Keep pushing forward.",
    "You're doing amazing. Keep moving towards your goals.",
    "Stay strong. Your efforts are making a difference.",
    "You're capable of achieving great things. Keep fighting.",
    "Keep going! Your dedication is paying off.",
    "You've come so far. Don't give up now.",
    "Each day you resist is a step closer to your goal.",
    "You're making wonderful progress. Keep up the great work.",
    "Believe in your ability to make this change. Keep going.",
    "You're doing fantastic. Stay committed and keep moving forward.",
    "Well done! You're making significant progress.",
    "Stay motivated. Your hard work is paying off.",
    "You've got this! Keep pushing forward.",
    "Believe in your strength. You're making progress every day.",
    "You're doing an incredible job. Keep up the effort.",
    "Stay strong. Each day brings you closer to success.",
    "You're making great strides. Keep moving forward.",
    "Your determination is inspiring. Keep going.",
    "You have the power to achieve your goals. Keep pushing.",
    "Well done! Your efforts are truly paying off.",
    "You're doing amazing. Keep up the hard work.",
    "Stay focused. You're making incredible progress.",
    "You've come a long way. Keep pushing forward.",
    "Each step you take is a victory. Keep going.",
    "Your commitment is impressive. Keep up the great work.",
    "Believe in yourself. You're on the path to success.",
    "You're making fantastic progress. Keep moving forward.",
    "Stay determined. You have the strength to succeed.",
    "Well done! Your dedication is making a difference.",
    "You're doing fantastic. Keep pushing towards your goals.",
    "Keep going! Your hard work is paying off.",
    "You're making great strides. Stay motivated.",
    "Believe in your journey. You're achieving amazing things.",
    "You're doing an outstanding job. Keep up the effort.",
    "Stay strong. You're on the path to success.",
    "You've got this! Keep moving towards your goals.",
    "Well done! Your dedication is truly admirable.",
    "You're making significant progress. Keep going.",
    "Stay focused. You're on the right path.",
    "You're doing great! Keep up the fantastic work.",
    "Keep going! Each day is a step closer to your goal.",
    "Believe in your ability to overcome this. You're doing great.",
    "You're making wonderful progress. Stay motivated.",
    "Well done! Your hard work is showing results.",
    "You're doing amazing! Keep pushing forward.",
    "Stay determined. You're making a real difference.",
    "You've got this! Keep moving forward.",
    "Excellent job! Your commitment is paying off.",
    "You're making fantastic strides. Keep up the hard work.",
    "Believe in yourself. You're on the path to success.",
    "You're doing great. Keep up the effort.",
    "Stay strong. Your dedication is making a difference.",
    "Well done! You're making incredible progress.",
    "You're on the right track. Keep going.",
    "Fantastic job! Your hard work is showing results.",
    "You're doing amazing! Keep pushing towards your goals.",
    "Stay motivated. You have the strength to succeed.",
    "You're making excellent progress. Keep up the effort.",
    "Well done! Your determination is truly admirable.",
    "You're doing great! Keep moving forward.",
    "Stay focused. Your hard work is paying off.",
    "You've got this! Keep pushing towards success.",
    "Fantastic effort! You're making significant progress.",
    "You're doing fantastic. Keep up the great work.",
    "Believe in your journey. You're making amazing strides.",
    "Keep going! Your dedication is truly inspiring.",
    "You're making wonderful progress. Stay strong.",
    "Well done! Your efforts are making a difference.",
    "You're doing an incredible job. Keep moving forward.",
    "Stay positive. You're on the path to success.",
    "You've got this! Keep up the hard work.",
    "Fantastic progress! Your dedication is paying off.",
    "You're doing amazing! Keep pushing forward.",
    "Well done! Your commitment is showing results.",
    "Stay motivated. You're making great strides.",
    "You're on the right track. Keep up the effort.",
    "Believe in yourself. You're achieving amazing things.",
    "You're making significant progress. Keep going.",
    "Excellent job! Your hard work is truly paying off.",
    "You're doing fantastic. Keep moving towards your goals.",
    "Stay focused. You have the strength to succeed.",
    "Well done! Your dedication is inspiring.",
    "You're making incredible strides. Keep going.",
    "Keep it up! Your efforts are making a real difference.",
    "You're doing great. Stay committed and keep moving forward.",
    "Believe in your journey. You're achieving wonderful things.",
    "You've got this! Keep pushing towards success.",
    "Fantastic work! Your hard work is paying off.",
    "You're making amazing progress. Keep up the effort.",
    "Stay strong. Your determination is making a difference.",
    "Well done! Your progress is truly inspiring.",
    "You're doing fantastic! Keep moving forward.",
    "Stay motivated. You're on the path to success.",
    "You've got this! Keep up the great work.",
    "Fantastic progress! Your commitment is paying off.",
    "You're doing amazing! Keep pushing towards your goals.",
    "Well done! Your hard work is showing results.",
    "Keep going! Your dedication is making a real difference.",
    "You're making great strides. Stay focused.",
    "Believe in yourself. You're achieving incredible things.",
    "You're doing fantastic. Keep moving forward.",
    "Stay strong. Your efforts are making a difference.",
    "Well done! Your progress is truly inspiring.",
    "You're making amazing progress. Keep up the hard work.",
    "Stay motivated. You're on the right path.",
    "You've got this! Keep pushing forward.",
    "Fantastic job! Your dedication is paying off.",
    "You're doing great. Keep up the excellent work.",
    "Believe in your ability to succeed. Keep moving forward.",
    "You're making significant progress. Keep going.",
    "Well done! Your commitment is truly admirable.",
    "You're doing amazing! Keep pushing towards your goals.",
    "Stay strong. Your hard work is showing results.",
    "You've got this! Keep up the effort.",
    "Fantastic progress! Your dedication is making a difference.",
    "You're doing great. Keep moving forward.",
    "Well done! Your determination is inspiring.",
    "You're making wonderful strides. Keep it up.",
    "Stay motivated. Your hard work is paying off.",
    "You're doing an incredible job. Keep going.",
    "Believe in your strength. You're achieving amazing things.",
    "You've got this! Keep pushing towards success.",
    "Fantastic work! Your progress is showing results.",
    "You're making excellent strides. Keep up the great effort.",
    "Well done! Your dedication is truly paying off.",
    "You're doing amazing! Keep moving forward.",
    "Stay focused. Your hard work is paying off.",
    "You've got this! Keep up the great work.",
    "Fantastic progress! Your commitment is inspiring.",
    "You're making great strides. Keep pushing forward.",
    "Well done! Your efforts are truly making a difference.",
    "Stay strong. Your determination is showing results.",
    "You're doing fantastic! Keep moving towards your goals."
];


export function getRandomMotivationalQuote() {
    const randomIndex = Math.floor(Math.random() * motivationalMessages.length);
    return motivationalMessages[randomIndex];
}



export function getRandomSupportiveQuote() {
    const randomIndex = Math.floor(Math.random() * supportiveMessages.length);
    return supportiveMessages[randomIndex];
}

